print("More About Boolean Data Type")
print("--------------------------------")
print("True and false are not the same as True and False in python")
print("--------------------------------")
print("Truth Table for Boolean Data Type")
print("--------------------------------")
print("True and True : ", True and True)
print("True and False : ", True and False)
print("False and True : ", False and True)
print("False and False : ", False and False)
print("--------------------------------")
print("True or True : ", True or True)
print("True or False : ", True or False)
print("False or True : ", False or True)
print("False or False : ", False or False)
